language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t garyclarke/dockerreact -f Dockerfile.dev .
script:
    - docker run -e CI=true garyclarke/dockerreact npm run test
deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "udemydocker"
    env: "Udemydocker-env"
    bucket_name: "elasticbeanstalk-eu-west-1-234290944523"
    bucket_path: "udemydocker"
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"